#!/bin/sh
# Autor: Rafael Vergani
# https://github.com/vergani/
# Data: 09/03/2024

echo "-----------------------------------------------"

echo "Obtendo genoma humano (hg38) para referência..."
wget -nc https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta

echo "-----------------------------------------------"


> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT] teste
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.


https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta

https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta 


## PIPELINE "IDEAL"?

![image](https://github.com/vergani/BioInfo/assets/35334365/828623b2-cd79-4064-89e9-3bd3fd9fb0f7)



## Setup Tools

bowtie2 - boa alternativa de alinhamento ao inves de usar bwa, mas precisa ter um indice pronto. (posso usar no galaxy qe é mais rápido).

minimap2 - até agora mais eficiente que encontrei para alinhar e mapear e cram. Testei com sucesso no galaxy

HISAT2 - ainda não testei no galaxy mas promete ser eficiente e rápido (acho que a saída é apenas BAM mesmo)

    sudo apt install samtools
    sudo apt install bwa
    sudo apt install bedtools
    sudo apt install fastp 


## Galaxy workflow

https://www.ncbi.nlm.nih.gov/sra/?term=exome

Access: publici

Source: DNA

Type: exome

paired

Plataform: 'optional'

Anotar o "accession number" caso precise voltar novamente no mesmo exome.

A coluna "run" tem um ID específico que serve para importar no galaxy (ex: SRR25306983)


Próximos passos:
- [x] Lorem ipsum
- [ ] Lorem ipsum
- [ ] Lorem ipsum



###  mais alguns rascunhos
## Convertendo, alinhando, mapeando e indexando

checar info interessante sobre CRAM ou BAM (se foi alinhado com HG38 ou HG19 por exemplo):

    samtools view -H sample.BAM/CRAM

Para criar índice usando bowtie2:

    bowtie2-build Homo_sapiens_assembly38.fasta Homo_sapiens_assembly38_bowtie2

Também posso baixar os índices prontos para usar no bowtie2:

    https://benlangmead.github.io/aws-indexes/bowtie

---

## HISAT2

A fast and sensitive alignment program
Aqui já vamos faze ro esquema de alinhar com os genes do arquivo GTF para a referencia:
  Selecionar fastq
  Print alignment summary to a file.
  Spliced alignment options (selecionar GTF do genoma de referência)

gerar um índice para o genoma de referencia:

    $ hisat2-build Homo_sapiens_assembly38.fasta Homo_sapiens_assembly38_hisat2

alternativamente, posso baixar os índices prontos aqui:
http://daehwankimlab.github.io/hisat2/download/

sintaxe alinhamento de dois fastq paired-end:

    $ hisat2 -x <index_prefix> -1 <read1.fastq> -2 <read2.fastq> -S <output.sam> 2> mapping_summary.txt

obs: "index_prefix" é o índice do genoma usado sem extensão no final do nome.

Ao abrir o arquivo mapping_summary.txt teremos um resumo interessante sobre nosso mapeamento:




agora vamos usar o `htseq` para ver o número de leituras de um gene em particulas naquele exoma



---

Para converter dois paired end fastq para sam e depois bam:

  bowtie2 -p 7 -x grch38_1kgmaj/grch38_1kgmaj -1 NG1P_1.fq.gz -2 NG1P_2.fq.gz -S NG-Vi-bowtie2-hg38.sam


Se for um single end (usar opção -U):

    bowtie2 -p 7 -x grch38_1kgmaj/grch38_1kgmaj -U DRR253030.fastq.gz -S DRR253030_bwt_hg38.sam
    samtools view -b DRR253030_bwt_hg38.sam -o DRR_bwt_hg38_sam.bam

After this step, you can further compress, index, and sort the BAM file using SAMtools:

    samtools sort alignment.bam -o alignment_sorted.bam
    samtools index alignment_sorted.bam

    minimap2 -t <threads> -x <preset> reference_index reads_R1.fastq reads_R2.fastq > alignment.sam


###  QualiMap BamQC 

Evaluate the quality of aligned reads data in BAM format. The tool summarizes basic statistics of the alignment (number of reads, coverage, GC-content, etc.) and produces a number of useful graphs for their interpretation.

checar esta ferramenta, nao sei se é a mesma
http://qualimap.conesalab.org/


